### PR TITLE
Some refactor + fix color brightness for light entity

### LINKED ISSUE #129: Make --paper-card-background-color the default off for color_type: card
See #128

### LINKED ISSUE #130: Make color: auto sensible to  brightness
See:
https://community.home-assistant.io/t/lovelace-button-card/65981/687

### PR DESCRIPTION
**Pull request by RomRider**
**Breaking Changes**
* The default color for the background of a card with `color_type: card` when the entity is `off` is now `var(--paper-card-background-color)`. Fixes #129 

**Fix**
* Fixes #130: `color: auto` uses also entity's brightness now

### CODE REVIEW

File: src/button-card.ts [hunk 1]
```diff
@@ -140,23 +52,7 @@ class ButtonCard extends LitElement {
...
-    }
-    const colorObj = new TinyColor(localColor);
-    let fontColor = ''; // don't override by default
-    if (colorObj.isValid && colorObj.getLuminance() > 0.5) {
-      fontColor = 'rgb(62, 62, 62)'; // bright colors - black font
-    } else {
-      fontColor = 'rgb(234, 234, 234)';// dark colors - white font
-    }
-    return fontColor;
+    return helpers.hasConfigOrEntityChanged(this, changedProps);
```
Comment (iantrich) [inline src/button-card.ts]: I'd prefer you remove `helpers.` and instead import the function explicitly. Just my preference though; your call
